### ISSUE TITLE
EventHandler fails to register with ServiceRegistry

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#178]
When trying to register the eventhandler with the service registry within my Docker cloud, I get the following error:

```
2020-02-05 07:21:52.807 ERROR d3534bc77d2b --- [           main] e.a.c.h.HttpService                      : Request returned with AUTH: Only public core system services are allowed to query directly. Requested service (event-publish-auth-update) is not!
2020-02-05 07:21:52.925 ERROR d3534bc77d2b --- [           main] o.s.b.SpringApplication                  : Application run failed
eu.arrowhead.common.exception.AuthException: Only public core system services are allowed to query directly. Requested service (event-publish-auth-update) is not!
	at eu.arrowhead.common.Utilities.createExceptionFromErrorMessageDTO(Utilities.java:469)
	at eu.arrowhead.common.http.ArrowheadHttpClientResponseErrorHandler.handleError(ArrowheadHttpClientResponseErrorHandler.java:53)
	[...]
	at eu.arrowhead.common.http.HttpService.sendRequest(HttpService.java:144)
	at eu.arrowhead.common.http.HttpService.sendRequest(HttpService.java:162)
	at eu.arrowhead.common.ApplicationInitListener.registerCoreSystemServicesToServiceRegistry(ApplicationInitListener.java:221)
	at eu.arrowhead.common.ApplicationInitListener.onApplicationEvent(ApplicationInitListener.java:91)
	[...]
	at eu.arrowhead.core.eventhandler.EventHandlerMain.main(EventHandlerMain.java:26)
	[...]
2020-02-05 07:21:53.169  INFO d3534bc77d2b --- [           main] e.a.c.ApplicationInitListener            : Service Registry is accessible...
2020-02-05 07:21:53.759 ERROR d3534bc77d2b --- [           main] e.a.c.h.HttpService                      : Request returned with INVALID_PARAMETER: No Service Registry entry with provider: (event_handler, 0.0.0.0:8444) and service definition: event-publish-auth-update exists.
2020-02-05 07:21:53.761  INFO d3534bc77d2b --- [           main] e.a.c.ApplicationInitListener            : Core system EVENT_HANDLER revoked 3 service(s).
```

The exception that causes the error in the ServiceRegistry is here: https://github.com/arrowhead-f/core-java-spring/blob/ce16b0d8c3ce65b062119f94628c3ca0cb80f71c/serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/security/SRAccessControlFilter.java#L100-L115

It seems to be caused by the EVENT_PUBLISH_AUTH_UPDATE_SERVICE constant located at https://github.com/arrowhead-f/core-java-spring/blob/ce16b0d8c3ce65b062119f94628c3ca0cb80f71c/core-common/src/main/java/eu/arrowhead/common/core/CoreSystemService.java#L36 not being present in the constant list PUBLIC_CORE_SYSTEM_SERVICES located at https://github.com/arrowhead-f/core-java-spring/blob/ce16b0d8c3ce65b062119f94628c3ca0cb80f71c/core-common/src/main/java/eu/arrowhead/common/CommonConstants.java#L121

**Comment by MaGaMeGa** [comment]
EVENT_PUBLISH_AUTH_UPDATE_SERVICE should certainly not be in the PUBLIC_CORE_SYSTEM_SERVICES list,
since it is not a public service.
The error is not reproducible at a Linux or Windows environment during EventHandler startup.

**Comment by emanuelpalm** [comment]
@MaGaMeGa I thought it should be in that list since the EventHandler tried to register that service without me explicitly configuring it to. I cannot see any section in the [`README.md`](https://github.com/arrowhead-f/core-java-spring/blob/master/README.md) explaining the why I would need to be aware of the existence of a public core system services list, so you have to excuse my ignorance.

@tsvetlin I'm using the `svetlint/eventhandler` Docker image, and am trying to make it connect to an instance of the `svetlint/serviceregistry` image. Perhaps the EventHandler image contains an old version?

**Comment by MaGaMeGa** [comment]
In an early version of the EventHandler, there was a bug, missing the EVENT_PUBLISH_AUTH_UPDATE_SERVICEfrom CoreSystemService.enums. It has been fixed around mid-October 2019. I would suggest to to use the latest version of the core systems.

**Comment by emanuelpalm** [comment]
Alright. @tsvetlin Will you update the docker image? Thank you.

**Comment by tsvetlin** [comment]
They are indeed old docker images uploaded into the Docker Hub. I'll build and upload the new images as soon as possible.

**Comment by emanuelpalm** [comment]
@tsvetlin @MaGaMeGa Even when building the eventhandler JAR from the latest commit in the development branch, the error persists for me. The new Docker image of @tsvetlin does not work either.

I am using my own certificates for all the systems. Could that be a problem? I'm just speculating. I created my own bash script for generating certificates, so none of the systems, including the eventhandler, are using the standard ones you provide.

This is the latest version of the script: https://github.com/emanuelpalm/ahf-conet/blob/master/demo-data-sharing/scripts/mk_certs.sh. This is a version I've used before: https://github.com/emanuelpalm/ahf-conet/blob/3101b9b1b5d80333fc47241a1804305832cde544/demo-data-sharing/scripts/mk_certs.sh. You might notice that I include the intended IP addresses, as well as custom DNS names, of all the systems as SubjectAlternativeNames

**Comment by emanuelpalm** [comment]
And, if any of you could explain to me how this is happening in the first place I would be grateful. Did I miss some section of the README.md in this repo? Do the core systems have some kind of special way of detecting and connecting to each other? I guess they do not require orchestration rules, right?

**Comment by tsvetlin** [comment]
![image](https://user-images.githubusercontent.com/15650896/74513174-4ab71080-4f0a-11ea-8e80-cce2a7ae1392.png)

This is the same JAR I used to build the docker image yesterday. The issue will be with your certificate.

**Comment by tsvetlin** [comment]
![Screenshot 2020-02-14 at 9 13 28](https://user-images.githubusercontent.com/15650896/74513255-7508ce00-4f0a-11ea-98d1-51f0f0a939cc.png)

I'm using the same JAR I built the docker image with yesterday. The problem is probably with your certificate.

**Comment by emanuelpalm** [comment]
But why would the certificate have an impact? And what is so special about the "event-publish-auth-update" service?

**Comment by tsvetlin** [comment]
Because it is trying to access a private endpoint. As listed in the error message: "Only public core system services are allowed to query directly." Something is wrong with the certificate. Could you please compare it with the default one, to see whats the difference?

**Comment by emanuelpalm** [comment]
Alright. I'll take a look.

**Comment by emanuelpalm** [comment]
The only difference I could find was the presence of a "Certificate Issuer", which seems to include some serial number of the issuer, in the "Authority Key Identifier" extension of your event handler certificate. I guess that serial number should be related to the cloud certificate? I'll see if I can make Java `keytool` create such a "Certificate Issuer" field.

**Comment by tsvetlin** [comment]
Or you could try to create one manually with KeyStore Explorer based on the guide. If that cert works try replicating it with the shell script. (Btw, that shell script would be a great addition to the framework ( you could create a PR to the scripts folder after the issue is fixed ;) )

**Comment by MaGaMeGa** [comment]
The system names in the certificates must be in line with the system names in the application.properties files. So, if you rename your system name in the certificate from service_registry to serviceregistry and from event_handler to eventhandler, please also change the system names in the application.properties accordingly.

**Comment by emanuelpalm** [comment]
@MaGaMeGa That could be it. I'll try!

**Comment by emanuelpalm** [comment]
@MaGaMeGa @tsvetlin That was it. The name in the certificate had to end with "event_handler". "eventhandler" wasn't good enough.

By the way, if I changed the "core_system_name" property in the .properties file for the event handler to "eventhandler", the system was outright rejected by the service registry for not being a core system.

Great!
